### ISSUE TITLE
Connection String

### ISSUE THREAD

**Issue by GordyGordy** [Lendix/heroku-buildpack-mongo#3]
Hi Lendix, this isn't really an issue. But I thought I would ask in case you were feeling helpful.

Any idea what the connection string would be after this is uploaded to Heroku?

Previous instances I've used, they give you one. This is free, which makes it awesome. :)

**Comment by jguepin** [comment]
Hello @GordyGordy,

The goal of this buildpack is not to run a MongoDB server instance, as Heroku dynos are not persistent. The goal is just to install MongoDB binaries on the dyno.

Our use-case is to use the `mongodump` command to backup a MongoDB database, hosted somewhere else.

**Comment by GordyGordy** [comment]
Ah I see. Also, Heroku dynos are not persistent, damn!


I will try mongolab and then see if I can figure out how to save stateful files on Heroku.


Really appreciate you getting back to me.


Gordy.

________________________________
